### PR TITLE
feat: add multiarch build using matrix strategy

### PR DESCRIPTION
**Pull request by zs-ko**
this pr adds multiple arch to the release workflow.

### CODE REVIEW

**Comment by siredmar** [comment]
@zs-ko thanks for providing this PR!

**Comment by siredmar** [comment]
@zs-ko the ARM build failed.
https://github.com/edgefarm/vault-plugin-secrets-nats/actions/runs/9349917143/job/25732313070
Would you mind having a look at this?

**Comment by siredmar** [comment]
release deleted

**Comment by zs-ko** [comment]
@siredmar it might be that the following is needed anyhow
@zs-ko
[ci: revert changee for generate.go. not needed to force arch](https://github.com/edgefarm/vault-plugin-secrets-nats/pull/29/commits/85ab55e99de02f42d18f323e7884a14583b5d781)

**Pull request merged**
